Feature/model processing addition
hytech-racing/simulink_automation pull request #1
Opened 2024-11-13 00:21 UTC by KrishKittur

2025-01-17 01:25 UTC, RCMast3r requested changes

2025-01-17 01:25 UTC, RCMast3r commented on .github/workflows/gen_code.yaml
> +          ref: feature/model_processing_addition
be sure to remove / changes this to master branch

2025-01-17 01:25 UTC, RCMast3r commented on Tire_Model_Codegen_inport_info.json
this looks like a generated file, was this meant to be pushed up?

2025-01-17 01:26 UTC, RCMast3r commented
also would you be able to add docs / a readme on how this gets used and / or what files you need to setup to get this to gen the stuff. even tho i started this i dont remember what i did lol

2025-02-13 11:56 UTC, RCMast3r requested changes

2025-02-13 11:56 UTC, RCMast3r commented on flake.nix
wait, why is the HT_proto flake in here with nanopb?

2025-02-13 11:56 UTC, RCMast3r commented on flake.nix
this should use the regular protobuf compiler and use nix-proto, nanopb is specifically for generating the C lib for the micros to use

2025-02-13 11:56 UTC, RCMast3r commented on json_to_proto.py
so while we will have estimation matlab models and control models, wont the proto template be used for both?

like to the simulink automation flow it shouldnt care about what type of model it is, just that it has outputs and some of them need to be given associated protobuf message members for logging / live telem so in this case shouldnt we rename estimation_msgs to something more general?

2025-02-13 11:56 UTC, RCMast3r commented on proto/estimation_msgs.proto.mako
> +import "nanopb.proto";
we shouldnt need nanopb here, this again is only for microcontroller messages. these messages wont be making it to the micros

2025-02-14 03:45 UTC, KrishKittur commented on json_to_proto.py
Yeah, this is how it will work. Sorry for the confusion earlier.

2025-02-14 04:21 UTC, RCMast3r approved these changes

2025-02-14 04:29 UTC, RCMast3r approved these changes

2025-02-21 13:54 UTC, RCMast3r requested changes

2025-02-21 13:54 UTC, RCMast3r commented on .github/workflows/gen_code.yaml
> +          cat Tire_Model_Codegen_inport_info.json
pls remove debug step

2025-02-21 13:54 UTC, RCMast3r commented on __pycache__/json_to_proto.cpython-312.pyc
pls remove this file

2025-02-21 13:54 UTC, RCMast3r commented on matlab_model/MatlabModelIntegration.cpp.mako
> +void estimation::${model}_MatlabModel::update_proto_info(${model}::ExtY_${model}_T res, std::shared_ptr<simulink_estimation_msgs::Outports> msg)
pls make_shared the msg pointer within this function and then return the shared_ptr instance.

also switch to making a different message type per-each model name

2025-02-21 13:54 UTC, RCMast3r commented on proto_outputs/Tire_Model_Codegen_estimation_msgs.proto
pls remove this output

2025-02-23 18:34 UTC, RCMast3r requested changes

2025-02-23 18:34 UTC, RCMast3r commented on .github/workflows/gen_code.yaml
> -  repository_dispatch
wont we want to keep this on repo dispatch?

2025-02-24 08:22 UTC, RCMast3r approved these changes
LGTM <3 :brain: 

we are thinking with portals now :portugal:

2025-03-02 23:17 UTC, merged